Repository capacitor-community/firebase-crashlytics, pull requests merged in 2021-04, with the labels that each got.

#24 chore: bump `firebase-crashlytics` version
  README.md
  android/build.gradle
Labels: dependencies

#25 feat(android): add support for project variables
  android/build.gradle
Labels: feature, platform: android

#23 feat: add Capacitor v3 support
  CapacitorCommunityFirebaseCrashlytics.podspec
  README.md
  android/build.gradle
  android/src/main/AndroidManifest.xml
  android/src/main/java/com/getcapacitor/community/firebasecrashlytics/FirebaseCrashlytics.java
  ios/Plugin.xcodeproj/project.pbxproj
  ios/Plugin/Plugin.swift
  ios/Podfile
  package-lock.json
  package.json
  src/index.ts
  src/web.ts
  tsconfig.json
Labels: breaking change, feature

#26 refactor: apply capacitor 3 plugin template
  .editorconfig
  .eslintignore
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/workflows/ci.yml
  .gitignore
  .npmrc
  .prettierignore
  CONTRIBUTING.md
  CapacitorCommunityFirebaseCrashlytics.podspec
  LICENSE
  PLUGIN_AUTHOR_README.md
  README.md
  android/.gitignore
  android/android.iml
  android/build.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.jar
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  android/gradlew.bat
  android/src/androidTest/java/com/getcapacitor/android/ExampleInstrumentedTest.java
  android/src/main/AndroidManifest.xml
  android/src/main/java/com/getcapacitor/community/firebasecrashlytics/FirebaseCrashlytics.java
  android/src/main/java/com/getcapacitor/community/firebasecrashlytics/FirebaseCrashlyticsPlugin.java
  android/src/main/res/.gitkeep
  android/src/main/res/layout/bridge_layout_main.xml
  android/src/main/res/values/colors.xml
  android/src/main/res/values/strings.xml
  android/src/main/res/values/styles.xml
  android/src/test/java/com/getcapacitor/ExampleUnitTest.java
  ios/Plugin.xcodeproj/project.pbxproj
  ios/Plugin.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  ios/Plugin.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ios/Plugin.xcodeproj/xcshareddata/xcschemes/Plugin.xcscheme
  ios/Plugin.xcodeproj/xcshareddata/xcschemes/PluginTests.xcscheme
  ios/Plugin/FirebaseCrashlytics.swift
  ios/Plugin/FirebaseCrashlyticsPlugin.h
  ios/Plugin/FirebaseCrashlyticsPlugin.m
  ios/Plugin/FirebaseCrashlyticsPlugin.swift
  ios/Plugin/Info.plist
  ios/PluginTests/FirebaseCrashlyticsPluginTests.swift
  package-lock.json
  package.json
  rollup.config.js
  src/definitions.ts
  src/index.ts
  src/web.ts
  tsconfig.json
Labels: refactor

#27 refactor(web)!: throw unimplemented error
  src/web.ts
Labels: breaking change, platform: web, refactor

#28 refactor(android)!: throw unimplemented error
  android/src/main/java/com/getcapacitor/community/firebasecrashlytics/FirebaseCrashlyticsPlugin.java
Labels: breaking change, platform: android, refactor

#29 refactor!: replace `iOSException` and `AndroidException`
  README.md
  src/definitions.ts
  src/web.ts
Labels: breaking change, refactor

#32 ci: set correct branch name
  .github/workflows/ci.yml
Labels: ci

#33 refactor(android): split plugin and implementation
  android/src/main/java/com/getcapacitor/community/firebasecrashlytics/FirebaseCrashlytics.java
  android/src/main/java/com/getcapacitor/community/firebasecrashlytics/FirebaseCrashlyticsPlugin.java
Labels: platform: android, refactor

#34 refactor(ios): split plugin and implementation
  CapacitorCommunityFirebaseCrashlytics.podspec
  README.md
  ios/Plugin.xcodeproj/project.pbxproj
  ios/Plugin.xcworkspace/contents.xcworkspacedata
  ios/Plugin/FirebaseCrashlytics.swift
  ios/Plugin/FirebaseCrashlyticsPlugin.swift
Labels: platform: ios, refactor

#35 ci: use nodejs 14
  .github/workflows/ci.yml
Labels: ci
